Add note about visually hidden text in styled radio group
tmobile/magentaA11y pull request #118
Opened 2024-02-20 17:57 UTC by joe-watkins

Adding notes to the SRG example

2024-02-22 18:00 UTC, silverli commented on _checklist-web/radio.md
> +  - <strong>Critical:</strong> Do not include this visually hidden text if the radio group does not consist of nested controls. It should not be present in the DOM. CSS <code>display: none;</code> is
I don't know if this is needed @joe-watkins. I think the comment in the code will be the most helpful thing for devs to cross check

2024-02-22 18:01 UTC, silverli requested changes
One quick thought for you

2024-02-22 18:01 UTC, silverli commented on _includes/examples/input-radio-styled-group.html
> +  <!-- This text should only be present in the DOM if the radio group has nested controls. Hiding it with CSS display: none; is not enough to hide it from screen readers. Ensure aria-describedby on t
This is great!

2024-02-22 18:01 UTC, silverli commented on _checklist-web/radio.md
> +  - <strong>Critical:</strong> Do not include this visually hidden text if the radio group does not consist of nested controls. It should not be present in the DOM. CSS <code>display: none;</code> is
I don't know if this is needed @joe-watkins. I think the comment in the code will be the most helpful thing for devs to cross check

2024-02-26 18:08 UTC, joe-watkins commented on _checklist-web/radio.md
> +  - <strong>Critical:</strong> Do not include this visually hidden text if the radio group does not consist of nested controls. It should not be present in the DOM. CSS <code>display: none;</code> is
@silverli Good call - I've removed this bullet

2024-02-26 18:09 UTC, merged