Expander hide details summary
tmobile/magentaA11y pull request #124
Opened 2024-02-29 19:35 UTC by joe-watkins

Due to a known bug with recent versions of iOS VoiceOver not announcing state we are encouraging use of ARIA Disclosure over Details/Summary until we get a few major versions beyond iOS 16-17.3

- Remove Details/Summary from Expander component page
- Convert Checklist accordions from Details/Summary to ARIA Disclosure 
- Note: Icon placement is different than Details/Summary but pretty much the same UX. A separate PR could be done to make those match exactly.

Will not be a ton of work to reintroduce Details/Summary down the road.

2024-02-29 19:43 UTC, tritland submitted a review, later dismissed

2024-03-15 23:23 UTC, silverli requested changes
Hey Joe, this is great! Thanks so much for making these changes. I had a couple suggestions. Additionally, should we keep the details/summary videos for a later use if we switch back to that pattern? Maybe rename them with an underscore? _expander.mp4a?  Also if we end up doing that, I'd leave a comment about it somewhere in the expander.md file

2024-03-15 23:23 UTC, silverli commented on _checklist-web/expander.md
> +**Note:** Due to known accessibility support issues in recent versions of iOS, `<details>` is not recommended for expander accordions. We recommend the use of an ARIA Disclosure Widget which has very
nice

2024-03-15 23:23 UTC, silverli commented on _layouts/checklist-native.html
> +            <button type="button" class="expander-toggle" aria-expanded="true" id="{{ category | escape }}-details" class="checklist-details">
Great catch. I notice the existing prod version had the carat turn pink on focus FYI and this is not doing that

2024-03-15 23:23 UTC, silverli commented on _layouts/checklist-native.html
> +            <div class="expander-content visible" aria-hidden="false">
aria-hidden feels unecessary here with CSS display block and none being toggled

2024-03-15 23:23 UTC, silverli commented on _layouts/checklist-web.html
> +                <strong><span aria-hidden="true">&lt;</span>{{ category | escape }}<span aria-hidden="true">&gt;</span></strong>
`<strong>` is also unexpected to me here. Would it be better to use CSS to impart this styling?

2024-03-15 23:23 UTC, silverli commented on _sass/modules/_details-summary.scss
> +// .fake-details addition
lol

2024-03-15 23:23 UTC, silverli commented on _layouts/checklist-native.html
> +            <button type="button" class="expander-toggle" aria-expanded="true" id="{{ category | escape }}-details" class="checklist-details">
(Not a huge deal, just noting the regression)

2024-07-18 16:43 UTC, joe-watkins commented on _layouts/checklist-native.html
> +            <button type="button" class="expander-toggle" aria-expanded="true" id="{{ category | escape }}-details" class="checklist-details">
Added magenta to :hover / :focus

2024-07-18 16:46 UTC, joe-watkins commented on _layouts/checklist-native.html
> +            <div class="expander-content visible" aria-hidden="false">
@silverli I agree but this appears to be an issue outside of the scope of this ticket if ya look at the file you called this out on `_layouts/checklist-native.html` Let's put a pin in this for now.

2024-07-18 16:47 UTC, joe-watkins commented on _layouts/checklist-web.html
> +                <strong><span aria-hidden="true">&lt;</span>{{ category | escape }}<span aria-hidden="true">&gt;</span></strong>
@silverli This is a change not applicable to this work and is more of a template issue. Let's put this off to the side for now :)

2024-07-18 16:49 UTC, joe-watkins commented
@silverli Fixes are in :) I've reintroduced the backed up videos and made sure the chevron is brand magenta on hover/focus. The other callouts were more template related so skipping for now.

2024-07-19 20:21 UTC, silverli approved these changes
Looks great!

2024-07-19 20:21 UTC, merged