Add success variant to Tidbit
tmobile/magentaA11y pull request #129
Opened 2024-03-07 20:38 UTC by joe-watkins

To support caution and error variants we are adding a success variant

2024-03-07 21:45 UTC, tritland submitted a review, later dismissed

2024-03-15 23:32 UTC, silverli requested changes
Great work, just a couple o' thoughts!

2024-03-15 23:32 UTC, silverli commented on _checklist-web/tidbit.md
> +- Ensure the SVG icon has a meaningful text alternative. e.g. <code>aria-label="Error"</code>, <code>aria-label="Caution"</code>, <code>aria-label="Success"</code>
might want to update Line 19 as well with this kind of "success" example - but it's not critical

2024-03-15 23:32 UTC, silverli commented on _includes/examples/tidbit-success.html
> +        <h2 id="tidbit-heading-error">That went well!</h2>
I'd change the id to "tidbit-heading-success"

same with aria-describedby reference below

2024-03-15 23:32 UTC, silverli commented on _sass/base/_colors.scss
> +$tdds-success-100: #E6FCE8;
I'm noticing the warning/caution icon color against the yellow background is not meeting 3:1. Maybe we can make the yellow background lighter or icon darker.

2024-05-03 18:40 UTC, joe-watkins commented
@silverli thanks for the fixes! Good catches. I've addressed them all.

2024-07-19 20:29 UTC, silverli approved these changes
Looks great!

2024-07-19 20:30 UTC, merged