Add button variant with live region support
tmobile/magentaA11y pull request #130
Opened 2024-03-08 02:02 UTC by joe-watkins

As noted in https://github.com/tmobile/magentaA11y/issues/125 it would be nice to have a variant that demonstrates live region support. I've added this example below the checkbox variant.

2024-03-16 00:43 UTC, silverli commented on _checklist-web/password-input.md
> +### Checkbox variant
I noticed that the type="password" input is incorrectly pointing its aria-describedby to the show-toggle name of "show password"

2024-03-16 01:00 UTC, silverli requested changes
Great work!! I've added a couple thoughts after running a screen reader through both examples. Thanks for your work on this suggestion @joe-watkins !!

2024-04-09 16:33 UTC, joe-watkins commented on _checklist-web/password-input.md
> +### Checkbox variant
This PR is not a refinement of the existing pattern but the addition of a new one - button based. A separate PR could be made to refine the checkbox variant.

2024-04-09 16:45 UTC, joe-watkins commented on _includes/examples/input-password-with-button.html
> +    <div id="password-visiblity-toggle-status" style="display: none;">
I've removed the non-visual helper text!

2024-04-09 16:48 UTC, joe-watkins commented on _checklist-web/password-input.md
> +  - The Live Region is seperately presenting the same state text but this text is removed from the DOM after a short pause so screen readers users don't also discover this redundant text. Due to scre
Fixed typo and removed blurb/gibberish that I think was in reference to `role="status"` support.

2024-04-09 16:51 UTC, joe-watkins commented on _checklist-web/password-input.md
> +  - If you use a Live Region ensure it does not own <code>aria-hidden="true"</code> or CSS <code>display: none;</code> as that impacts screen reader support. Remove contents after a small timeout so
Good call! I've bumped it up into those general notes :)

2024-04-09 16:52 UTC, joe-watkins commented
@silverli Back to you! thanks for the fixes!

2024-07-19 20:44 UTC, silverli requested changes
2 last things!! Sorry

2024-07-19 20:44 UTC, silverli commented on _includes/examples/input-password-with-button.html
> +            <button class="tertiary" type="button" aria-describedby="password-visiblity-toggle-status">
@joe-watkins sorry can we remove this aria-describedby as well?

2024-07-19 20:44 UTC, silverli commented on _checklist-web/password-input.md
> +  - The button is describedby by non-visual text in the code via <code>aria-describedby</code>. This container owns CSS <code>display: none;</code>. While we can still reference it on the toggle butt
And remove this mention of the aria-describedby since we removed it

2024-07-19 20:47 UTC, jzoo approved these changes
looks good

2024-07-19 21:18 UTC, joe-watkins commented
@silverli Thank you! I've removed `aria-describdeby` and updated/trimmed the text content as well!

2024-07-23 14:08 UTC, silverli approved these changes
Approved!

2024-07-23 14:08 UTC, merged