Content revision joe
tmobile/magentaA11y pull request #161
Opened 2024-10-14 21:48 UTC by joe-watkins

Copy edits to AC for the following Web components:

**html**
- Basic web page
- Footer landmark
- Form
- Header landmark
- Main landmark
- Navigation landmark
- Skip link

**header**
- Header landmark
- Navigation landmark
- Search input

**nav**
- Breadcrumbs
- Button
- Link
- Navigation landmark
- Pagination nav
- Search input

2024-10-15 19:02 UTC, tritland approved these changes

2024-12-24 21:52 UTC, silverli requested changes
ok one small question/issue raised on the search! sorry this took me so long to review 😛 

great job!

2024-12-24 21:52 UTC, silverli commented on _checklist-web/form.md
> -  mode:  |
👍

2024-12-24 21:52 UTC, silverli commented on _checklist-web/nav.md
> +      tab is used to browse the navigation menu
👍

2024-12-24 21:52 UTC, silverli commented on _checklist-web/search.md
> +    Search button is activated [if present]
I think lines 12 and 14 are flipped? should be about the search in line 12 and the search button for line 14? because space inside the search field would just add a space to the string being searched

2024-12-24 21:52 UTC, silverli commented on _checklist-web/search.md
> +    Focus moves to the search text input and search button [if present] and there is a highly visible visual indication of keyboard focus
I also find this all a bit confusing where we are saying focus is moving to both the search field AND the button. I feel like we should focus on the input behavior and make any mention of the button explicit and clear

2025-07-16 20:25 UTC, brisourceful commented
Closing this issue to be added as task to transpose the edits into the new repo.

2025-07-16 20:25 UTC, closed without merging