Remove generic text from How To Test page
tmobile/magentaA11y pull request #64
Opened 2023-08-14 22:45 UTC by joe-watkins

Removed generic text from the How To Test page to simplify.

2023-09-05 17:14 UTC, joe-watkins commented
@tritland @silverli  This PR just basically removes the big chunk of text below the cards. It felt a little obligatory and felt strange just dangling below the new cards Charlie added.

2023-09-12 23:27 UTC, silverli requested changes
One question!

2023-09-12 23:27 UTC, silverli commented on how-to-test.md
> -Accessibility testing is important because it helps to ensure that everyone can use a website or application, regardless of their disability. This includes people who are blind, deaf, have low vision
do you think this text would fit on the "Not sure it's an issue page?"

2023-09-27 16:57 UTC, tritland submitted a review, later dismissed

2023-09-28 21:01 UTC, joe-watkins commented on how-to-test.md
> -Accessibility testing is important because it helps to ensure that everyone can use a website or application, regardless of their disability. This includes people who are blind, deaf, have low vision
@silverli Good idea! I've added it to the Not Sure page ;) https://github.com/tmobile/magentaA11y/pull/64/commits/f5d30ca9555d2b6e585d52de383058bdca0b4bfb

2023-10-02 20:03 UTC, tritland approved these changes

2023-10-06 21:11 UTC, silverli approved these changes
approved!

2023-10-06 21:11 UTC, silverli commented on how-to/not-sure-if-it-is-an-issue.md
> +Accessibility testing is important because it helps to ensure that everyone can use a website or application, regardless of their disability. This includes people who are blind, deaf, have low vision
great!

2023-10-06 21:14 UTC, merged