Add new stepper component
tmobile/magentaA11y pull request #69
Opened 2023-09-01 23:20 UTC by joe-watkins

1. Reintroduced standard Select with traditional Select look and feel 
3. Changed markup order to match visual order so things land as button > select > button 
4. Converted fake buttons into real buttons 
5. Added a visually hidden live container to support dynamic updates 
6. Changed non-visual button labels to "decrease" "increase" from "more/less" and included context - decrement/increment not plain language
7. Updated Gherkin, condensed, and WCAG How to test
8. Updated Dev notes
9. Removed lessons learned

2023-09-05 20:41 UTC, tritland approved these changes

2023-09-11 18:53 UTC, silverli commented on _checklist-web/stepper-input.md
> +      the tab key to move focus form fields
maybe instead
When I use
> the tab key to move focus

OR 

When I use
> the tab key to move focus to the first interactive item

2023-09-11 19:03 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +      the tab key to move focus form fields
@silverli Good call!

2023-09-11 19:08 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +      the tab key to move focus form fields
Updated ;) https://github.com/tmobile/magentaA11y/pull/69/commits/52b9d92e4b3494e98efabde732072883f3fc1bc2

2023-09-11 19:16 UTC, silverli requested changes
This is looking fantastic. I had a couple ideas/suggestions so let me know if you want to make some changes based on those! Also ok if you want to pass on some on some of them for now!

2023-09-11 19:16 UTC, silverli commented on _checklist-web/stepper-input.md
> +This component is useful for small-ish selections. If the max count is more than 20, this component will be cumbersome for people using a mouse.
I might adjust the wording of small-ish just to ensure clarity. Perhaps instead:

> This component is useful for small range increments.

2023-09-11 19:16 UTC, silverli commented on _checklist-web/stepper-input.md
> +### Speciality stepper integer input
Before, or in this section, I would recommend saying something like:

> Before using this pattern, consider if using a plain <select> (link to magentaA11y select) might be more clear and simple for all users. A select does everything that this stepper does, and with less code! Plus, a select is native and accessible out of the box.

2023-09-11 19:16 UTC, silverli commented on _checklist-web/stepper-input.md
> +This component is useful for small-ish selections. If the max count is more than 20, this component will be cumbersome for people using a mouse.
Also say what pattern to use if the increment is more than 20

2023-09-12 00:09 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +This stepper example provides both `button` and `select` elements for users to change a value.
Converted to list :) tnx!

Removed nested visually hidden text in trade for `aria-label` no longer need to explain .hidden class.

I've pushed a commit which expands on how the text in the live region is generated.

2023-09-12 00:10 UTC, joe-watkins commented on _includes/examples/input-select-stepper.html
> +  <!-- live container -->
@silverli This message didn't make the trip - can you remember what you were thinking here?

2023-09-12 00:11 UTC, joe-watkins commented on _includes/examples/input-select-stepper.html
> +  <button class="button minus">
I've cooked up some very messy JS for this - whole thing could use a refactor down the road, works for now.

https://github.com/tmobile/magentaA11y/pull/69/commits/e7a2dbf439ba95669ee7bb66aa726ecbda39d9bd

2023-09-12 00:13 UTC, joe-watkins commented on assets/scripts/index.js
> +    function removeStepperLiveMessage(delay){
@silverli If this content was visual it sure could be - or probably even a 4.1.3 Status Message too, but since the value of the form field is on the page and persists regardless of how long the live container message lives in the DOM we can think of this as an extra feature, there is an accessible alternative - screen reader users must dig around for that after interaction though.

2023-09-12 00:14 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +This component is useful for small-ish selections. If the max count is more than 20, this component will be cumbersome for people using a mouse.
Done! Updated content and included a note about using a text input as an alternative.

2023-09-12 00:14 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +### Speciality stepper integer input
Done! https://github.com/tmobile/magentaA11y/pull/69/commits/e7a2dbf439ba95669ee7bb66aa726ecbda39d9bd

2023-09-12 00:15 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +The `button` `aria-label` values should be plain text and they should include context of what they affect when activated (typically the label for the `select`).  e.g. Increase Quantity, Add Quantity
Done! tnx ;) https://github.com/tmobile/magentaA11y/pull/69/commits/e7a2dbf439ba95669ee7bb66aa726ecbda39d9bd

2023-09-12 00:16 UTC, joe-watkins commented
@silverli Pull latest! I've addressed your awesome ideas. Just one comment above.

2023-09-12 19:58 UTC, silverli commented on _includes/examples/input-select-stepper.html
> +  <!-- live container -->
Oh shoot!.. @joe-watkins meant to say:
` <! live container where "Quanity updated, {x}" will be dynamically updated -->`

2023-09-12 20:00 UTC, silverli commented on _includes/examples/input-select-stepper.html
> +  <button class="button minus">
wow amazing!!

2023-09-12 20:06 UTC, silverli requested changes
Ok! Sorry just a few more ideas based on your awesome changes/including of disabled buttons!!

2023-09-12 20:06 UTC, silverli commented on _checklist-web/stepper-input.md
> +      - criteria: The disabled and focus states have a 3:1 minimum contrast ratio against default
not a big deal, but just letting you know your grey #cccccc for the disabled doesn't pass against white background https://webaim.org/resources/contrastchecker/?fcolor=CCCCCC&bcolor=FFFFFF not sure if it matters but I could see reading this as failing this criteria

2023-09-12 20:06 UTC, silverli commented on _checklist-web/stepper-input.md
> +- This stepper example provides both `button` and `select` elements for users to change a value.
sorry will you also include a bullet about the aria-disabled attribute now that it's been included? something like:
* aria-disabled="true" will be applied to the buttons when either end of the range is reached

2023-09-12 20:06 UTC, silverli commented on assets/scripts/index.js
> +    function removeStepperLiveMessage(delay){
Ok thank you! That makes sense!

2023-09-12 20:06 UTC, silverli commented on _checklist-web/stepper-input.md
> +Before using this pattern, consider if using a plain [Select dropdown](https://www.magentaa11y.com/checklist-web/select/) which might be more clear and simple for all users. A select does everything
Tiny tiny change:
> Before using this pattern, consider if using a plain [Select dropdown](https://www.magentaa11y.com/checklist-web/select/) ~which~ might be more clear and simple for all users

2023-09-12 23:09 UTC, joe-watkins commented on _includes/examples/input-select-stepper.html
> +  <!-- live container -->
Added! :) tnx

2023-09-12 23:11 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +      - criteria: The disabled and focus states have a 3:1 minimum contrast ratio against default
Good catch. Via CSS, I've tweaked the "disabled" control to meet at least 3:1. Dark +/- now.

2023-09-12 23:11 UTC, joe-watkins commented on _checklist-web/stepper-input.md
> +Before using this pattern, consider if using a plain [Select dropdown](https://www.magentaa11y.com/checklist-web/select/) which might be more clear and simple for all users. A select does everything
Fixed! Good catch.

2023-09-12 23:11 UTC, joe-watkins commented
@silverli Back to you! Thanks for more great callouts. I've folded those in :) :) :)

2023-09-12 23:22 UTC, silverli commented on _checklist-web/stepper-input.md
> +      - criteria: The disabled and focus states have a 3:1 minimum contrast ratio against default
I was actually thinking about the contrast between the background behind the control, but changing the minus / plus is very good too! Maybe that's actually enough to make this pass anyways

2023-09-13 15:28 UTC, silverli commented on _checklist-web/stepper-input.md
> +      - criteria: The disabled and focus states have a 3:1 minimum contrast ratio against default
Decided that yes, the minus/plus alone having 3:1 contrast in enough!

2023-09-13 15:28 UTC, silverli approved these changes
Great job @joe-watkins. This is an awesome resource!

2023-09-13 15:47 UTC, merged