Recode radio buttons with nested controls
tmobile/magentaA11y pull request #70
Opened 2023-09-07 22:42 UTC by joe-watkins

This PR includes a recode of the special use case [Radio mixed with interactive elements](https://www.magentaa11y.com/checklist-web/radio/#specialty-use-cases). The goal is to move away from the ARIA Checkbox approach in trade for more traditional Radio buttons.

While keyboard focus order is not ideal, because of the design anti-pattern, standard keyboard functionality for Radio buttons (up/down/right/left) arrows and other accessibility wins are now present.

Changes/Improvements:
- Native Radio buttons instead of checkboxes with radio roles
- Native / expected keyboard support for Radio
- Number of options available now communicated to screen reader
- No longer triggering accessibility violations in some automated accessibility testing engines due to missing ARIA `aria-checked`
- Pattern no longer breaks ARIA use rules [#1 and #2](https://www.w3.org/TR/using-aria/#firstrule)
- Reduced risk but not by much
- Visually hidden content informing screen reader users about nearby controls

2023-09-11 14:44 UTC, tritland submitted a review, later dismissed

2023-09-12 22:16 UTC, silverli requested changes
This is an awesome change, @joe-watkins. Thanks for putting in the work and making the case. Just a couple suggestions/edits!

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
I would mention that the use of the same `name` attribute is important to link the radio buttons as a programmatic group! Some devs might not know this.

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
> +- Ensure the nested controls also have additional context defined by <code>aria-describedby</code>. This will help screen reader users understand their purpose.
I think you got rid of the aria-describedby stuff for inputs in your code

2023-09-12 22:16 UTC, silverli commented on _includes/examples/input-checkbox-radio.html
>        payment method alpha
I might recommend using `aria-describedby` on the button instead and giving it the id of the radio button such as "checkboxRadioAlpha2" so it says "Edit, Alpha, button"

Just seems a bit cleaner. But might want to make a note of how to give buttons unique names in these different ways in the notes above.

2023-09-12 22:16 UTC, silverli commented on _includes/examples/input-checkbox-radio.html
>        payment method alpha
or aria-labelledby

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
> +**Avoid** placing interactive elements between radio buttons. Radio groups are not supposed to consist of nested interactive elements.
Avoid this pattern when possible! Maybe let's be a little more strong with the opinion just to scare people!

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
> +- Radio button focus order is not what you may expect
I'm not sure what this means

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
> +- Radio button focus order is not what you may expect
Maybe if this sentence is combined with the next one. That makes it a bit clearer

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
> +- As soon as a radio button is selected, the selected radio input receives focus first from the group. As a result screen reader users may not discover a nested control for an option.
Maybe a bit more clear:
> As a result screen reader users may not discover a nested control for an option if they start switching between radio buttons alone.

2023-09-12 22:16 UTC, silverli commented on _checklist-web/radio.md
> +- To try to mitigate screen reader users not discovering the nested controls, describe the fieldset / radiogroup with non-visual text. This can be done with <code>aria-describedby</code> on the <code
And then mention the text you have recommended to associate with the fieldset "Edit controls are available which follow each radio button"

2023-09-13 15:57 UTC, joe-watkins commented on _checklist-web/radio.md
> +- Ensure the nested controls also have additional context defined by <code>aria-describedby</code>. This will help screen reader users understand their purpose.
@silverli This lives higher up that you might have noticed, it is on the `fieldset` instead of each input and is present.

2023-09-13 16:07 UTC, joe-watkins commented on _checklist-web/radio.md
Done! tnx :)

2023-09-13 16:07 UTC, joe-watkins commented on _checklist-web/radio.md
> +- Ensure the nested controls also have additional context defined by <code>aria-describedby</code>. This will help screen reader users understand their purpose.
Done! tnx :)

2023-09-13 16:07 UTC, joe-watkins commented on _checklist-web/radio.md
> +**Avoid** placing interactive elements between radio buttons. Radio groups are not supposed to consist of nested interactive elements.
Done! tnx :)

2023-09-13 16:08 UTC, joe-watkins commented on _checklist-web/radio.md
> +- Radio button focus order is not what you may expect
Cleaned this up a bit

2023-09-13 16:08 UTC, joe-watkins commented on _checklist-web/radio.md
> +- As soon as a radio button is selected, the selected radio input receives focus first from the group. As a result screen reader users may not discover a nested control for an option.
Love it! Done!

2023-09-13 16:08 UTC, joe-watkins commented on _checklist-web/radio.md
> +- To try to mitigate screen reader users not discovering the nested controls, describe the fieldset / radiogroup with non-visual text. This can be done with <code>aria-describedby</code> on the <code
Done! tnx :)

2023-09-13 16:09 UTC, joe-watkins commented
@silverli I've addressed your awesome feedback :)

2023-09-13 16:46 UTC, merged