Add web tidbit component
tmobile/magentaA11y pull request #77
Opened 2023-10-04 19:33 UTC by joe-watkins

Adding a new Web Tidbit component

2023-10-04 19:34 UTC, joe-watkins commented
@silverli @tritland Created a Tidbit - ready for review!

2023-10-08 18:14 UTC, tritland submitted a review, later dismissed

2023-10-11 21:09 UTC, silverli requested changes
This is an awesome new component to add to MagentaA11y! Thanks, Joe :) A couple comments and suggestions included in my review

2023-10-11 21:09 UTC, silverli commented on _checklist-web/tidbit.md
> +    There is no grouping for the Tidbit
Is this relevant? Since the coding example here doesn't utilize role="region" I feel like this may not be necessary

2023-10-11 21:09 UTC, silverli commented on _checklist-web/tidbit.md
> +- <strong>Icon:</strong> Ensure that the info icon has a text alternative. Add <code>role="img"</code> and <code>aria-label="Info"</code> to the SVG.
I feel like this is going against the guidance here: http://localhost:4000/checklist-web/image-decorative/ maybe we should discuss on coaches meeting or magentaa11y standup

2023-10-11 21:09 UTC, silverli commented on _checklist-web/tidbit.md
> +- <strong>Link:</strong> If the link in the Tidbit is a generic "Learn more" "More info" style link, ensure that it is programmatically associated with the nearby heading with <code>aria-describedby<
Would you consider adding a sentence at the end such as: 
> Consider linking the heading instead of using a "learn more" link to clean up the design and make the link text more descriptive for all users!
?

2023-10-11 21:09 UTC, silverli commented on _checklist-web/tidbit.md
> +    - If for some reason the Tidbit does not have a heading but still has a link at the bottom of the Tidbit, it is required that the link text be meaningful and avoid use of "Learn more" "Read more"
Maybe a nitpick, but could you clarify this part to say something like:
> If for some reason the Tidbit does not have a heading but still has a link at the bottom of the Tidbit outside the paragraph,

2023-10-11 21:09 UTC, silverli commented on _checklist-web/tidbit.md
> +    - If for some reason the Tidbit does not have a heading but still has a link at the bottom of the Tidbit, it is required that the link text be meaningful and avoid use of "Learn more" "Read more"
Oh actually.. maybe remove this point completely since you have the specific example and developer note below about this case

2023-10-11 21:09 UTC, silverli commented on _checklist-web/tidbit.md
> +    There is no grouping for the Tidbit
If it is relevant, I would make a note of it in the developer notes as well

2023-10-11 22:54 UTC, joe-watkins commented on _checklist-web/tidbit.md
> +- <strong>Icon:</strong> Ensure that the info icon has a text alternative. Add <code>role="img"</code> and <code>aria-label="Info"</code> to the SVG.
@silverli If the Tidbit had the word "Info" as part of the heading text right next to the icon that would a decorative image. We are describing it because it screams "info" visually. It kind of also acts as a "heads up" for screen reader users since we aren't going the named `region` route. 

In my opinion, it follows guidance nicely with the content found at: http://localhost:4000/checklist-web/image-decorative/ 

> If the image conveys important meaning, and there’s no other text on the page which explains the concept within it, then the image is likely informative.

Additionally, I'm trying to get the TDDS team to lean more towards describing important icons (error and warning) - this aligns with that

2023-10-11 22:55 UTC, joe-watkins commented on _checklist-web/tidbit.md
> +    There is no grouping for the Tidbit
Yes, I do feel this is relevant and plays with this content found in the Developer Notes:

<strong>Icon:</strong> Ensure that the info icon has a text alternative. Add <code>role="img"</code> and <code>aria-label="Info"</code> to the SVG.

2023-10-11 22:58 UTC, joe-watkins commented on _checklist-web/tidbit.md
> +- <strong>Link:</strong> If the link in the Tidbit is a generic "Learn more" "More info" style link, ensure that it is programmatically associated with the nearby heading with <code>aria-describedby<
@silverli I myself am not a fan of making headings clickable without providing some sort of visual treatment to that so folks know they are interactive. A CTA I think jumps out to users more. How do you envision the look and feel for that if we were to introduce an option?

2023-10-11 23:00 UTC, joe-watkins commented on _checklist-web/tidbit.md
> +      the Tidbit scrolls into view
Fixed! Good call :)

2023-10-11 23:01 UTC, joe-watkins commented on _checklist-web/tidbit.md
> +    There is no grouping for the Tidbit
It also ensure the tester is thinking about the role of heading and that there isn't any semantic grouping element.

2023-10-11 23:03 UTC, joe-watkins commented on _checklist-web/tidbit.md
> +    - If for some reason the Tidbit does not have a heading but still has a link at the bottom of the Tidbit, it is required that the link text be meaningful and avoid use of "Learn more" "Read more"
Removed that chunk of content ;)

2023-10-16 15:00 UTC, silverli commented on _checklist-web/tidbit.md
> +- <strong>Link:</strong> If the link in the Tidbit is a generic "Learn more" "More info" style link, ensure that it is programmatically associated with the nearby heading with <code>aria-describedby<
Ah got it! I was thinking an underline with the heading but no worries. Just an idea for another example

2023-10-16 15:01 UTC, silverli approved these changes
Looks great!

2023-10-16 15:04 UTC, silverli commented on _checklist-web/tidbit.md
> +- <strong>Icon:</strong> Ensure that the info icon has a text alternative. Add <code>role="img"</code> and <code>aria-label="Info"</code> to the SVG.
Ah actually.. the example on the decorative page has "note" as part of the heading text... I think that's about equivalent to the "i" icon

2023-10-18 00:05 UTC, merged