How to test: Images
tmobile/magentaA11y pull request #78
Opened 2023-10-06 22:10 UTC by joe-watkins

New How to Test content page:

- Added Images CTA to `/how-to-test/`
- Created Images how to test page

2023-10-08 17:57 UTC, tritland commented on how-to/images.md
> +## <step-number>3</step-number> Meaningful Images
We refer to these as "Informative Images" above and on the home page. Should we keep that language consistent here?

2023-10-08 18:04 UTC, tritland commented on how-to/images.md
> +- **Note:** Sometimes functional images may have empty or null alt attribute value <code>alt=""</code> and this is ok **if** what text would be the text alternative is moved to the parent control's l
The wording here is a bit confusing. Maybe adjust to something like:
"Functional images can have empty or null alt attributes if the text alternative is conveyed in the parent control's label. For example..." or similar?

2023-10-08 18:08 UTC, tritland commented on how-to/images.md
> +  <p><strong>Note:</strong> The passing chart has a general text alternative describing what the image is but also references nearby text data for reference. <code>alt="Fruit chart, data below"</code
Typo: "The failing example owns an **empty** alt attribute...

2023-10-08 18:09 UTC, tritland approved these changes

2023-10-09 22:36 UTC, joe-watkins commented on how-to/images.md
> +## <step-number>3</step-number> Meaningful Images
Nice! Fixed in https://github.com/tmobile/magentaA11y/pull/78/commits/bc593cc23e7adab66d28dc5cd12eecfeba25e81c

2023-10-09 22:36 UTC, joe-watkins commented on how-to/images.md
> +- **Note:** Sometimes functional images may have empty or null alt attribute value <code>alt=""</code> and this is ok **if** what text would be the text alternative is moved to the parent control's l
Nice! Fixed in https://github.com/tmobile/magentaA11y/pull/78/commits/bc593cc23e7adab66d28dc5cd12eecfeba25e81c

2023-10-09 22:36 UTC, joe-watkins commented on how-to/images.md
> +  <p><strong>Note:</strong> The passing chart has a general text alternative describing what the image is but also references nearby text data for reference. <code>alt="Fruit chart, data below"</code
Nice! Fixed in https://github.com/tmobile/magentaA11y/pull/78/commits/bc593cc23e7adab66d28dc5cd12eecfeba25e81c

2023-10-11 21:23 UTC, silverli commented on how-to/images.md
> +- **Images of Text:** It's generally recommended to avoid putting text within images because it can be challenging for some users. However, if you must use images with text, ensure that the alt text
Maybe we should say "Images of text should be avoided whenever possible" and that it will violate a WCAG SC. And then However... :)

2023-10-11 21:43 UTC, silverli requested changes
Great work! A couple comments and suggestions included

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +- Open DevTools in your browser window (<span class="keyboard-key">F12</span>)
does this work for safari/firefox/ etc?

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +- Ensure that the <code>alt</code> attribute is present is not empty.
I might add:
> Ensure that the <code>alt</code> attribute is present is not empty, such as `alt` or `alt=""`

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +- The <code>alt</code> attribute value / description of the image should be accurate and succinct. It should not consist of information that is not imnportant or duplicates nearby text content.
Double "not" here! haha just a little confusing. I might reword to say in the second sentence:
> The image alternative should not consist of information that duplicates nearby text content.

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +- Typically, the text is the most important part of the image. There is no need for the image itself to be described unless it adds value to the content of the page.
Maybe we can add another comment about:
> Consider logging a defect for [Images of Text 1.4.5](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html) if it seems like there might be a viable workaround to add real text to the page vs. an image of text.

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +{:/}
Should this section get a little pseudo code example with a <table>...</table> and the text alternative for the chart image above?

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +Some images are implemented using inline <code>SVG</code>. Text alernatives for these images can be defined by use of <code>role="img"</code> and <code>aria-label="I am the alt text"</code>. The <cod
English major moment!
> whose

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +  alt="Titanium Apple iPhone 15 Pro"/>
Maybe this can be done in another PR but I'm noticing at tablet/smaller breakpoints, these are not resizing and causing multiple scrollbars

2023-10-11 21:43 UTC, silverli commented on how-to/images.md
> +- 1.1.1 Non-text Content
maybe this is another PR worth of work too, but I feel like we should link to WCAG

2023-10-11 23:12 UTC, joe-watkins commented on how-to/images.md
> +- **Images of Text:** It's generally recommended to avoid putting text within images because it can be challenging for some users. However, if you must use images with text, ensure that the alt text
@silverli I love it! tnx ;)

2023-10-11 23:13 UTC, joe-watkins commented on how-to/images.md
> +- Open DevTools in your browser window (<span class="keyboard-key">F12</span>)
@silverli I wish :) Added "Chrome"

2023-10-11 23:14 UTC, joe-watkins commented on how-to/images.md
> +- Ensure that the <code>alt</code> attribute is present is not empty.
@silverli Agreed!

2023-10-11 23:15 UTC, joe-watkins commented on how-to/images.md
> +- The <code>alt</code> attribute value / description of the image should be accurate and succinct. It should not consist of information that is not imnportant or duplicates nearby text content.
@silverli for reals! Tnx ;)

2023-10-11 23:16 UTC, joe-watkins commented on how-to/images.md
> +- Typically, the text is the most important part of the image. There is no need for the image itself to be described unless it adds value to the content of the page.
Yes! Added ;)

2023-10-11 23:21 UTC, joe-watkins commented on how-to/images.md
> +{:/}
Indeed! Added a little table example.

2023-10-11 23:22 UTC, joe-watkins commented on how-to/images.md
> +Some images are implemented using inline <code>SVG</code>. Text alernatives for these images can be defined by use of <code>role="img"</code> and <code>aria-label="I am the alt text"</code>. The <cod
Nice :) tnx soo much :) Fixed

2023-10-11 23:22 UTC, joe-watkins commented on how-to/images.md
> +  alt="Titanium Apple iPhone 15 Pro"/>
@silverli I think there is a separate card for that already.

2023-10-11 23:23 UTC, joe-watkins commented on how-to/images.md
> +- 1.1.1 Non-text Content
@silverli This would be a separate PR and I think we have strayed from it previously to reduce having to keep up with URLs, but that would be nice - especially if they pointed to 2.2 links.

2023-10-13 18:13 UTC, merged