Add new single link card example
tmobile/magentaA11y pull request #80
Opened 2023-10-13 23:15 UTC by joe-watkins

Added a new single-link product card (driven by `aria-labelledby` and `aria-describedby`) to the Product Card example page and some accessibility barrier notes about the pre-existing card example (which feels like an [Inclusive Components Card](https://inclusive-components.design/cards/) hybrid) because it presents WCAG 2.5.3 Label in Name issues as well as text-to-speech barriers.

2023-10-13 23:27 UTC, joe-watkins commented on _includes/examples/product.html
> +        <svg style="display: inline-block;" role="img" aria-label="Promo" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><path d="M0 80V229.5c0 17 6.7 33.3 18.7 45.3l176 176c25
Describing this icon because it supports the text as the text alone doesn't callout that it is a promo

2023-10-13 23:28 UTC, joe-watkins commented on _includes/examples/product.html
> +          <ul id="colors" class="product-colors" aria-hidden="true">
Hiding colors to reduce verbosity - all colors would be available on PDP in real life - instead using plain language "# colors available"

2023-10-14 00:10 UTC, joe-watkins commented on _includes/examples/product.html
> +      aria-labelledby="prod-0-eyebrow prod-0-name"
Reduce accessible name to brand and product name. Avoid stuffing the Accessible Name so Voice Recognition users have a better chance at activating the control.

2023-10-14 00:11 UTC, joe-watkins commented on _includes/examples/product.html
> +      aria-describedby="prod-0-meta-rating prod-0-meta-network prod-0-colors product-0-price-monthly product-0-price-today product-0-price-full">
Move rest of card content to the Accessible Description which is announced after the Accessible Name but does not interfere with voice users [Voice Control].

2023-10-14 00:11 UTC, joe-watkins commented on _includes/examples/product.html
> +      aria-labelledby="prod-0-eyebrow prod-0-name"
Also, does not clutter links list

2023-10-26 15:43 UTC, silverli requested changes
Couple of thoughts! The link web-checklist page will need to be updated with these changes OR a new product card web-checklist component page should be made.

2023-10-26 15:43 UTC, silverli commented on _includes/examples/product.html
> +<p>This card is a single link and does not consist of any other nested controls. Use of <code>aria-labelledby</code> and <code>aria-describedby</code> to control how the card is announced by screen r
Hey @joe-watkins this is all showing up on the link web-checklist page. Which makes me think 1 of 2 more things should happen:
1. Should product card be its own component? It's so highly used and there's at least 2 variations... I could see that.
2. Otherwise, we need to update the text of the link page. I would include your descriptions there instead of on the demo page.

2023-10-26 15:43 UTC, silverli commented on _includes/examples/product.html
> +<h2 class="h-bravo">Product Card with multiple controls</h2>
can we just remove the "see details" fake button? I like everything else about this example "Product Card with multiple controls"

2023-10-26 15:43 UTC, silverli commented on _includes/examples/product.html
> +<p><strong>Note:</strong> This approach works well for screen reader users but introduces challenges for voice recognition users because the fake "See Details" button is hidden from assistive technol
if we did make a product card component page, we could add a third variation where we suggest no link wrapping and just a regular card where the heading is the link 😂

2023-11-14 21:43 UTC, joe-watkins commented on _includes/examples/product.html
> +<p>This card is a single link and does not consist of any other nested controls. Use of <code>aria-labelledby</code> and <code>aria-describedby</code> to control how the card is announced by screen r
@silverli I've simplified the Links checklist page by taking out a few bullets to let the working examples and the code below tell the story. **Note**: I've also touched the content above that was related to generic links while I was in there.

I've also elevated the approach that I think you and @tritland might be a bit more comfortable with [Heading with link] and the all-in-one-link approach is below that. I've also removed some intro text to clean things up too. 

Lastly, I've removed the fake button from the original pattern.

2023-11-14 21:43 UTC, joe-watkins commented on _includes/examples/product.html
> +<h2 class="h-bravo">Product Card with multiple controls</h2>
Removed ;)

2023-11-14 21:45 UTC, joe-watkins commented on _includes/examples/product.html
> +<p><strong>Note:</strong> This approach works well for screen reader users but introduces challenges for voice recognition users because the fake "See Details" button is hidden from assistive technol
I like keeping this off to the side a bit as just a demo to be less opinionated in a way

2023-11-14 21:48 UTC, joe-watkins commented
@silverli @tritland I've taken a stab at cleaning things up again for another review.

2023-11-21 16:37 UTC, tritland approved these changes

2023-11-22 18:00 UTC, silverli requested changes
Everything is looking great. Just 2 really small edits if you don't mind @joe-watkins!!

2023-11-22 18:00 UTC, silverli commented on _checklist-web/link.md
> +- Instead, make the heading a link or programmatically associate the link with the heading using <code>aria-describedby</code>.
I just noticed this, but could we add headings above the code examples of good and bad right below here? They are unfortunately only indicated by color right now

2023-11-22 18:00 UTC, silverli commented on _includes/examples/product.html
> +<ul class="product-list multiple-controls">
this `<ul>` structure shows up in the code block on the link example page and it's a bit confusing. I think it should be removed as it was being used to style 3 examples across in a row on the demo page.

2023-11-22 18:00 UTC, silverli commented on _includes/examples/product.html
> -          See details
YAY!!!!!

2023-11-28 22:27 UTC, silverli commented on _checklist-web/link.md
> +- Instead, make the heading a link or programmatically associate the link with the heading using <code>aria-describedby</code>.
Great job @joe-watkins this is great!!

2023-11-28 22:30 UTC, silverli approved these changes
Looks fantastic. Let's ship it! 🚀

2023-11-28 22:30 UTC, silverli commented on _includes/examples/product.html
> +<ul class="product-list multiple-controls">
Much better!!!

2023-11-28 23:20 UTC, merged