Web - Make breadcrumbs responsive
tmobile/magentaA11y pull request #98
Opened 2024-01-04 20:47 UTC by joe-watkins

- Ensured breadcrumbs hold up at 320 by just stacking them
- Removed unnecessary `aria-label` on one of the links while under the hood

2024-01-16 22:02 UTC, silverli requested changes
just one small change! Good fixes!!

2024-01-19 22:18 UTC, joe-watkins commented on _sass/modules/_nav-breadcrumbs.scss
> +    @media(min-width: $key-breakpoint){
@silverli Thanks a million! I was not aware of those - awesome! I've worked that in.

2024-01-19 22:18 UTC, joe-watkins commented
@silverli Thanks so much! Good catch on the breakpoint. Fixed :) Ready for review!

2024-01-22 15:54 UTC, silverli approved these changes
Looks great!

2024-02-26 18:10 UTC, merged