Update textarea to support sidecar screen reader support
tmobile/magentaA11y pull request #99
Opened 2024-01-10 20:40 UTC by joe-watkins

- Added a visually hidden container that is updated dynamically after a slight pause
- Hide visible container from screen readers
- Updated AC and text content in the page
- Adjusted JS to accommodate the new approach

2024-01-16 22:45 UTC, silverli commented on _checklist-web/textarea.md
> +  status: |
One question/thought:

Can we have one example on this page with a textarea with a maxlength which needs the status update/ and then another example with a regular textarea that does not require a text counter? Seems weird to have only one example which is more complex and requires extra HTML/ARIA. 

At the very least, I feel that we should mention this case is more complex because there is a maxlength requirement, or some reason along those lines. Thoughts?

2024-01-16 23:38 UTC, silverli requested changes
A couple of thoughts and comments! Great work as always! ✨

2024-01-16 23:38 UTC, silverli commented on _checklist-web/textarea.md
> +- <strong>Note:</strong> There are two containers in the HTML that have the same counter content. One of them is hidden from screen readers by use of `aria-hidden="true"` and the other visually hidde
maybe also make a note here that you can still reference an element that is hidden with aria-hidden with aria-describedby and it will  still read out when the screen reader reaches the textarea.

2024-01-16 23:38 UTC, silverli commented on _checklist-web/textarea.md
> +  - Use `setTimeout`to allow the accessibility tree and screen reader time to update in a logical fashion e.g. 1500ms
I would also reword this a bit maybe like so:
> **Delay the update** for dynamic `role="status"` counter
  - Use `setTimeout` to allow the accessibility tree and screen reader time to update the status information in a logical fashion e.g. 1500ms

2024-01-19 22:01 UTC, joe-watkins commented on _checklist-web/textarea.md
> +  status: |
@silverli I think your ideas are good ones and that could be a separate ticket due to the level of effort

2024-01-19 22:08 UTC, joe-watkins commented on _checklist-web/textarea.md
> +- <strong>Note:</strong> There are two containers in the HTML that have the same counter content. One of them is hidden from screen readers by use of `aria-hidden="true"` and the other visually hidde
Good call!

2024-01-19 22:12 UTC, joe-watkins commented
@silverli Thank you for the review and great ideas - I've addressed them :) take a peek!

2024-01-22 16:27 UTC, silverli commented on _checklist-web/textarea.md
> +  status: |
@joe-watkins I made a new asana task for this and put it in the backlog!

2024-01-22 16:30 UTC, silverli approved these changes
Looks great!

2024-01-25 21:42 UTC, merged